### ISSUE TITLE
There is no way to disable optional dependencies

### ISSUE THREAD

**Issue by khaledhosny** [centricular/freetype2#1]
I’m not very well versed in meson, so excuse me if I missed the obvious. I can’t find anyway to disable optional dependencies, especially when used as subproject. For example when used as a subproject in a project that also has a harfbuzz subproject, both freetype and harfbuzz will have a circular dependency on each other and I don’t see a way around it if one can’t turn off the optional support for one of the features (HarfBuzz is needed by FreeType only for autohinting, so for projects that use FreeType only to load the fonts, the HarfBuzz dependency can be skipped).

**Comment by MathieuDuponchelle** [comment]
That is correct: when these build definitions were written, support for "feature" options in meson hadn't been merged yet, and we decided to make all options automatic. Now that feature options have landed, we can now expose optional dependencies as feature options, patches welcome :)

**Comment by khaledhosny** [comment]
If you can point me to the relevant documentation, or an example, I can try to come up with a patch.

**Comment by MathieuDuponchelle** [comment]
Documentation:

http://mesonbuild.com/Build-options.html#features

Test case:

https://github.com/mesonbuild/meson/tree/master/test%20cases/common/198%20feature%20option 

Real world usage:

https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/blob/master/meson_options.txt#L54
https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/blob/master/ext/alsa/meson.build#L10
https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/blob/master/ext/alsa/meson.build#L12

Cheers :)

**Comment by tp-m** [comment]
Are you taking a stab at this @khaledhosny ?

If you don't have time let me know and I can have a look.

**Comment by khaledhosny** [comment]
I’m trying to fix other build issues right now, and was planing to look into this issue right after that, but if you can work on it that would be even better.

**Comment by tp-m** [comment]
Added options, and rebased from on top of 9e345c911714ed62250be13d03d72e25d91fbc77 to on top of 8d517e679b65a9f4b85abf995045cf76cb8b5354

**Comment by khaledhosny** [comment]
Works fine, thanks!
